# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  mirnaapp:
    image: mirnaapp
    build:
      context: .
      dockerfile: MirnaApp/Dockerfile
    ports:
      - 5131:5131
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
